services:
  db:
    image: postgres
    container_name: madclothes
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madclothes
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
