services:
  postgres-development:
    image: postgres
    container_name: postgres-development
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-development-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    container_name: postgres-test
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres-test"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-development-data:
  postgres-test-data:
