services:
  db:
    image: postgres
    container_name: madclothes
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_DB: $TYPEORM_DATABASE
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
