services:
  postgres-development:
    image: postgres
    container_name: postgres-development
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-development-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    container_name: postgres-test
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres-test"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

  redis-development:
    image: redis
    container_name: redis-development
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-development-data:/var/lib/redisql/data

  redis-test:
    image: redis
    container_name: redis-test
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-test-data:/var/lib/postgresql/data

volumes:
  postgres-development-data:
  postgres-test-data:
  redis-development-data:
  redis-test-data:
