name: CD

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Heroku (staging)
      if: github.ref == 'refs/heads/staging'
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: madclothes-api-staging

    - name: Run migrations (staging)
      if: github.ref == 'refs/heads/staging'
      run: heroku run npx typeorm migration:run -a madclothes-api-staging


    - name: Deploy to Heroku (prod)
      if: github.ref == 'refs/heads/main'
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: madclothes-api-prod

    - name: Run migrations (prod)
      if: github.ref == 'refs/heads/prod'
      run: heroku run npx typeorm migration:run -a madclothes-api-prod
